### ISSUE TITLE
permissions issues on unRAID

### ISSUE THREAD

**Issue by argash** [seanap/auto-m4b#18]
After running the initial mp3 -> m4b conversion I cannot MOVE the file to the merge folder I can only copy it. Looks like the permissions aren't being set properly. Any ideas on how to resolve this?

**Comment by seanap** [comment]
It's definitely a permissions issue, same as this discussion https://github.com/seanap/auto-m4b/discussions/17

This docker isn't respecting the environment variables set in the config file for some reason.  It works for me on Ubuntu 20, so I wonder if it's something in unraid.  I don't have unraid to test, but does it help to open a shell or the permissions plugin, and CHOWN 0775 all the input/output and config folders?

**Comment by argash** [comment]
DOH my bad some how my eye's glazed write past that issue!. Yup same exact issue. So chown did work but I had to do:

`chown 0755 -R *` followed by `chown nobody:users -R *`

I'm going to do another test with just the user:group later after I convert another book

**Comment by argash** [comment]
Ok can confirm ONLY `chown nobody:users -R *` is needed

**Comment by seanap** [comment]
Awesome, thank you for testing!
