### ISSUE TITLE
Feature Request:  Chapters from MusicBrainz or Custom-Settings (File)

### ISSUE THREAD

**Issue by TheMBeat** [seanap/auto-m4b#2]

**Comment by seanap** [comment]
Mbz in my experience has an extreemly limited audiobook database, and only a small fraction of the audiobooks have chapter data.  It's best to pull chapter information from Audnexus which stores chapter metadata directly from the Audible API.  That said tagging is out of the scope of this utility for now, for tagging proper chapternames the Audible Beets.io plugin is the tool for that job.

Interesting idea about a custom-settings file.  This will export the chapters assigned to the m4b.  It would be cool if we could edit that chapters file manually with the chapter names, put that file in the book folder, and re-run that book through m4b-tool (by moving the book folder to `/temp/merge` ).  It wouldn't be automated but it at least gives a straight forward way to edit and embed chapters.  

I'm not sure how to actually implement this though, I will look into maybe adding an IF statement to look for a `chapters.txt` file in the folder and then run a modified m4b-tool command, ELSE do things as they are now.

Great idea! I'll leave this open till something is implemented

**Comment by seanap** [comment]
Give this new build a try.  What I did was have the script check `/temp/merge` for book folders that contain a `*.chapters.txt` file, if it does it will re-chapterize the m4b based on the *.chapters.txt fie.

### To use:

1. Put a folder with mp3's in the `/temp/recentlyadded` and let the script process the book like normal
2. In the output folder ( `/temp/untagged` ) there will be a book folder that includes the recently converted *.m4b and a *.chapters.txt file.
3. Open the chapters file and edit/add/rename, then save
4. Move the book folder (which contains the m4b and chapters.txt files) to `/temp/merge`
5. When the script runs it will re-chapterize the m4b and move it back to `/temp/untagged`

Let me know how it goes

**Comment by TheMBeat** [comment]
Sorry for the late reply... unfortunately I could not test it yet. Nevertheless, thanks again for the quick implementation.
