### ISSUE TITLE
auto-m4b doesnt seem utilize cover.jpg

### ISSUE THREAD

**Issue by amlucent** [seanap/auto-m4b#52]
auto-m4b doesnt seem utilize cover.jpg as outlined at https://github.com/sandreas/m4b-tool?tab=readme-ov-file#step-2---add-cover-and-a-description

**Comment by Sparh4wk** [comment]
ofc not, its striping them. if u read the sh script, its only processing  mp3, m4b or m4a files.

**Comment by seanap** [comment]
That's correct, this tool is really just to combine and chapterize. The file/folder naming, metadata, and tags are best left to dedicated tools. I like using beets.io audible plugin to quickly get it in the right folder structure, then ABS to actually look up the metadata and write to file. 

There were way too many edge cases that made trying to use m4b-tool to tag old non-standard mp3s a nightmare to automate.  I found most of the included covers to be sub par in size and quality vs what abs can pull so I just strip it.

**Comment by Sparh4wk** [comment]
@amlucent yet u can still edit the sh script to move cover.jpg and remove --skip-cover to process it
